apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "oai-spgwu-tiny.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "oai-spgwu-tiny.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "oai-spgwu-tiny.selectorLabels" . | nindent 8 }}
      annotations:
        k8s.v1.cni.cncf.io/networks: {{ .Chart.Name }}-{{ .Values.namespace }}-net1, {{ .Chart.Name }}-{{ .Values.namespace }}-net2, {{ .Chart.Name }}-{{ .Values.namespace }}-net3
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
      - name: tcpdump
        image: corfr/tcpdump
        command:
          -  /bin/sh
          -  -c
          -  /usr/sbin/tcpdump -i any -C 100 -W 10 -w /pcap/SPGWU_`date +%Y-%m-%d_%H_%M-%S-%Z`.pcap
          # -  /usr/sbin/tcpdump -i any port 2152 or port 8805 or port 5001 or arp or icmp -C 100 -W 10 -w /pcap/SPGWU_`date +%Y-%m-%d_%H_%M-%S-%Z`.pcap
        volumeMounts:
        - mountPath: "/pcap"
          name: {{ .Chart.Name }}-{{ .Values.namespace }}-pv
      - name: spgwu
        image: "{{ .Values.image.repository }}:{{ .Values.image.version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
        ports:
        - containerPort: {{ .Values.service.pfcpPort }}
          name: oai-spgwu
        - containerPort: {{ .Values.service.gtpuPort }}
          name: s1u
        env:
          - name: PID_DIRECTORY
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: pidDirectory
          - name: SGW_INTERFACE_NAME_FOR_S1U_S12_S4_UP
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: sgwS1uIf
          - name: SGW_INTERFACE_NAME_FOR_SX
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: sgwSxIf
          - name: PGW_INTERFACE_NAME_FOR_SGI
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: pgwSgiIf
          - name: NETWORK_UE_IP
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: netUeIp
          - name: NETWORK_UE_NAT_OPTION
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: netUeNatOption
          - name: SPGWC0_IP_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: pgwcSxIp
          - name: PGWU_SGI_GW
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: pgwuSgiGw
        #volumeMounts:
        #- mountPath: /dev/hugepages
        #  name: hugepage
        {{- with .Values.resources }}
        resources:
        {{- toYaml . | nindent 10 }}
        {{- end }}
      volumes:
        - name: {{ .Chart.Name }}-{{ .Values.namespace }}-pv
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-{{ .Values.namespace }}-pvc   
        # - name: hugepage
        #   emptyDir:
        #    medium: HugePages            
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: {{ .Values.serviceAccount.name }}
      terminationGracePeriodSeconds: 15
      # Real-Time worker node
      nodeName: dedale.5glab.nsa.eurecom.fr
      