---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Chart.Name}}
  labels:
    {{- include "magma-oai-mme.labels" . | nindent 4}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      {{- include "magma-oai-mme.selectorLabels" . | nindent 6}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "magma-oai-mme.selectorLabels" . | nindent 8}}
      annotations:
        k8s.v1.cni.cncf.io/networks: {{.Chart.Name}}-{{.Values.namespace}}-net1, {{.Chart.Name}}-{{.Values.namespace}}-net2
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8}}
    {{- if .Values.imagePullSecrets}}
      imagePullSecrets:
        {{- toYaml . | nindent 8}}
    {{- end}}
      containers:
      - name: tcpdump
        image: corfr/tcpdump
        volumeMounts:
          - mountPath: "/pcap"
            name: {{.Chart.Name}}-{{.Values.namespace}}-pv
        command:
          -  /bin/sh
          -  -c
          -  /usr/sbin/tcpdump -i any -C 100 -W 10 -w /pcap/magma-oai-mme_`date +%Y-%m-%d_%H_%M-%S-%Z`.pcap
      - name: sctpd
        image: "{{.Values.image.repository}}:{{.Values.image.version}}"
        volumeMounts: 
          - name: shared-data
            mountPath: "/tmp/sctpd"
        command:
          -  /bin/sh
          -  -c
          -  rm -Rf /tmp/sctpd/*; /usr/sbin/sctpd; sleep 15;
      - name: redis
        image: "{{.Values.image.repository}}:{{.Values.image.version}}"
        command:
          - /usr/bin/redis-server
          - /usr/local/etc/redis/redis.conf
      - name: mme
        image: "{{.Values.image.repository}}:{{.Values.image.version}}"
        imagePullPolicy: {{.Values.image.pullPolicy}}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12}}
        ports:
        - containerPort: {{.Values.service.diameterPort}}
          name: magma-oai-mme
        - containerPort: {{.Values.service.diameterSecPort}}
          name: oai-mme-sec
        - containerPort: {{.Values.service.gtpcPort}}
          name: s11
        env:
          - name: PREFIX
            value: {{.Values.mmeConf.prefix}}
          - name: MME_FQDN
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name}}-{{.Values.namespace}}-configmap
                key: mmeService
        volumeMounts:
          - mountPath: "/magma/etc/mme_fd.conf"
            name: fd-vol
            subPath: mme_fd.conf
            readOnly: false
          - mountPath: "/magma/etc/mme.conf"
            name: cfg-vol
            subPath: mme.conf
            readOnly: false
          - name: shared-data
            mountPath: "/tmp/sctpd"
        {{- with .Values.resources}}
        resources:
        {{- toYaml . | nindent 10}}
        {{- end}}
        command:
          -  /bin/sh
          -  -c
          -  /magma/bin/oai_mme -c /magma/etc/mme.conf
      volumes:
        - name: {{.Chart.Name}}-{{.Values.namespace}}-pv
          persistentVolumeClaim:
            claimName: {{.Chart.Name}}-{{.Values.namespace}}-pvc
        - configMap:
            name: mme-cfg-configmap
          name: cfg-vol
        - configMap:
            name: mme-fd-configmap
          name: fd-vol
        - name: shared-data
          emptyDir: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: {{.Values.serviceAccount.name}}
      terminationGracePeriodSeconds: 30
      nodeName: perse.5glab.nsa.eurecom.fr

