apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "oai-mme.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "oai-mme.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "oai-mme.selectorLabels" . | nindent 8 }}
      annotations:
        k8s.v1.cni.cncf.io/networks: {{ .Chart.Name }}-{{ .Values.namespace }}-net1, {{ .Chart.Name }}-{{ .Values.namespace }}-net2
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
      - name: mme
        image: "{{ .Values.image.repository }}:{{ .Values.image.version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        ports:
        - containerPort: {{ .Values.service.diameterPort }}
          name: oai-mme
        - containerPort: {{ .Values.service.diameterSecPort }}
          name: oai-mme-secure
        - containerPort: {{ .Values.service.gtpcPort }}
          name: s11
        env:
          - name: INSTANCE
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: instance
          - name: OUTPUT
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: output
          - name: PREFIX
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: prefix
          - name: PID_DIRECTORY
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: pidDirectory
          - name: MME_FQDN
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: mmeService
          - name: HSS_FQDN
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: hssService
          - name: REALM
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: mmeRealm
          - name: MME_GID
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: mmeGid
          - name: MME_CODE
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: mmeCode
          - name: MME_INTERFACE_NAME_FOR_S1_MME
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: nwIfS1c
          - name: MME_INTERFACE_NAME_FOR_S11
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: nwIfS11
          - name: MME_INTERFACE_NAME_FOR_S10
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: nwIfS10
          - name: MCC
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: mcc
          - name: MNC
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: mnc
          - name: MCC_SGW_0
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: mcc
          - name: MNC3_SGW_0
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: mnc3
          - name: MNC3_MME_0
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: mnc3_mme0
          - name: MNC3_MME_1
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: mnc3_mme0
          - name: MCC_MME_0
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: mcc_mme0
          - name: MCC_MME_1
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: mcc_mme1
          - name: TAC_0
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: tac_0
          - name: TAC_1
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: tac_1
          - name: TAC_2
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: tac_2
          - name: TAC_LB_SGW_0
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: tac_0_lb
          - name: TAC_HB_SGW_0
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: tac_0_hb
          - name: TAC_LB_SGW_1
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: tac_1_lb
          - name: TAC_HB_SGW_1
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: tac_1_hb
          - name: TAC_LB_SGW_2
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: tac_2_lb
          - name: TAC_HB_SGW_2
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: tac_2_hb
          - name: TAC_LB_SGW_TEST_0
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: tac_0_lb
          - name: TAC_HB_SGW_TEST_0
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: tac_0_hb
          - name: TAC_LB_MME_0
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: tac_lb_mme0
          - name: TAC_HB_MME_0
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: tac_hb_mme0
          - name: TAC_LB_MME_1
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: tac_lb_mme1
          - name: TAC_HB_MME_1
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: tac_hb_mme1
          - name: MME_IPV4_ADDRESS_FOR_S1_MME
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: mmeIpS1c
          - name: MME_S6A_IP_ADDR
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: mmeIpS1c
          - name: MME_IPV4_ADDRESS_FOR_S11
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: mmeIpS11
          - name: MME_IPV4_ADDRESS_FOR_S10
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: mmeIpS10
          - name: PEER_MME_IPV4_ADDRESS_FOR_S10_0
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: peerMme0Ipv4Address
          - name: PEER_MME_IPV4_ADDRESS_FOR_S10_1
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: peerMme1Ipv4Address
          - name: SGW_IPV4_ADDRESS_FOR_S11_0
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: sgwIpS11
          - name: HSS_REALM
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: hssRealm
          - name: HSS_HOSTNAME
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: hssHostname
          - name: HSS_IP_ADDR
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: hssIp
      - name: tcpdump
        image: corfr/tcpdump
        command:
          -  /bin/sh
          -  -c
          -  /usr/sbin/tcpdump -i any port 36412 or port 2123 or port {{ .Values.service.diameterPort }} -C 100 -W 10 -w /pcap/MME_`date +%Y-%m-%d_%H_%M-%S-%Z`.pcap
        volumeMounts:
        - mountPath: "/pcap"
          name: {{ .Chart.Name }}-{{ .Values.namespace }}-pv
      volumes:
        - name: {{ .Chart.Name }}-{{ .Values.namespace }}-pv
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-{{ .Values.namespace }}-pvc          
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: {{ .Values.serviceAccount.name }}
      terminationGracePeriodSeconds: 15
      nodeName: perse.5glab.nsa.eurecom.fr

