apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "oai-spgwc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "oai-spgwc.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "oai-spgwc.selectorLabels" . | nindent 8 }}
      annotations:
        k8s.v1.cni.cncf.io/networks: {{ .Chart.Name }}-{{ .Values.namespace }}-net1, {{ .Chart.Name }}-{{ .Values.namespace }}-net2
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
      - name: spgwc
        image: "{{ .Values.image.repository }}:{{ .Values.image.version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        ports:
        - containerPort: {{ .Values.service.pfcpPort }}
          name: oai-spgwc
        - containerPort: {{ .Values.service.gtpcPort }}
          name: s11
        env:
          - name: PID_DIRECTORY
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: pidDirectory
          - name: PGW_INTERFACE_NAME_FOR_SX
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: pgwSxIf
          - name: SGW_INTERFACE_NAME_FOR_S11
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: sgwS11If
          - name: SGW_IP_FOR_S5_S8_CP
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: sgwS5S8Ip
          - name: PGW_IP_FOR_S5_S8_CP
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: pgwS5S8Ip
          - name: UE_IP_ADDRESS_POOL
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: ueIpAddressPool
          - name: DEFAULT_APN
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: apn
          - name: DEFAULT_DNS_IPV4_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: ueDnsServer
          - name: DEFAULT_DNS_SEC_IPV4_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: ueDnsServerSec
      - name: tcpdump
        image: corfr/tcpdump
        command:
          -  /bin/sh
          -  -c
          -  /usr/sbin/tcpdump -i any port 2123 or port 8805 or arp or icmp -C 100 -W 10 -w /pcap/SPGWC_`date +%Y-%m-%d_%H_%M-%S-%Z`.pcap
        volumeMounts:
        - mountPath: "/pcap"
          name: {{ .Chart.Name }}-{{ .Values.namespace }}-pv
      volumes:
        - name: {{ .Chart.Name }}-{{ .Values.namespace }}-pv
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-{{ .Values.namespace }}-pvc   
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: {{ .Values.serviceAccount.name }}
      terminationGracePeriodSeconds: 15

