---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition 
metadata:
  name: {{ .Chart.Name }}-{{ .Values.namespace }}-net1
spec:
  config: '{ 
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "bond0",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
                {
                        "address": {{- cat .Values.lte.sgwIpSx "/" .Values.lte.sgwNetmaskSx | nospace | quote }},
                        "gateway": {{ .Values.lte.sgwGatewaySx | quote }}
                }
        ]
      }
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition 
metadata:
  name: {{ .Chart.Name }}-{{ .Values.namespace }}-net2
spec:
  config: '{ 
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "bond0",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
                {
                        "address": {{- cat .Values.lte.sgwIpS11 "/" .Values.lte.sgwNetmaskS11 | nospace | quote }},
                        "gateway": {{ .Values.lte.sgwGatewayS11 | quote }}
                }
        ]
      }
    }'
